Pantalla records
GreatSoldier99/Escape2D pull request #1
Opened 2021-12-07 05:55 UTC by GreatSoldier99

En este commit se corrigio la clase RecordsManager para que funcione de forma correcta, se agrego un efecto de transparencia a los botones y se agrego la clase BackButton, la cual crea un boton que nos permite regresar al menu principal.

2021-12-07 06:35 UTC, iuresti requested changes

2021-12-07 06:35 UTC, iuresti commented on HelpButton.java
> +        super.act();
Si solo llamas al método del papá, sería mejor no sobre escribirlo aqui

2021-12-07 06:35 UTC, iuresti commented on Records.txt
> +Juan 25
Este archivo no debes subirlo a github... Borralo porfas y añádelo al gitignore

2021-12-07 18:54 UTC, GreatSoldier99 commented
Ya realice los cambios profesor.

2021-12-09 00:27 UTC, iuresti approved these changes

2021-12-09 00:27 UTC, iuresti commented on Label.java
> +        labelText=record.getNamePlayer()+splitter+Integer.toString(record.getScorePlayer());
no es necesario que lo cambies, pero se prefiere usar Integer.parseInt a Integer.toString

2021-12-09 00:27 UTC, iuresti commented on MenuScreen.java
> +    private static GreenfootSound music = new GreenfootSound("menu.mp3");
si quieres que sean constantes recuerda usar "final"

2021-12-09 00:58 UTC, merged